### ISSUE TITLE
Scale of read value -ppm

### ISSUE THREAD

**Issue by freeck** [drug123/T67XX#1]
I purchased a T6703-2K version of the sensor. The library and example work fine!
The values read seem te be too high, outside in open air I measure 500 ppm, what should be around 400 ppm....could be related to the first weeks calibration proces....I hope.
In case I breath out close to the sensor I measure values exceeding 2000 ppm,and even more than 5000 ppm!?

[https://www.amphenol-sensors.com/en/telaire/co2/525-co2-sensor-modules/3215-t6700](url)

**Comment by drug123** [comment]
Hi,
According to manufacturer specs, you should leave it working during around 7 days to have it properly self-calibrated. 
Try it :)
