### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Kabron287** [drug123/T67XX#2]
```  
Wire.begin(Address);      // NO SUCH FUNCTION
uint8_t status = Wire.status();   // NO SUCH FUNCTION
```
correct and working code is
```
  uint8_t status =   Wire.begin(SDA, SCL);
```

**Comment by drug123** [comment]
Hi,

> uint8_t status = Wire.status();   // NO SUCH FUNCTION

This will be corrected in next release.

> Wire.begin(Address);      // NO SUCH FUNCTION

It seems you're using ESP32 Wire.h version. AVR and ESP8266 both have corresponding overloaded methods. I'll update this one for better compatibility with ESP platforms.
